### Create Note
POST http://localhost:3000/notes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzMxNTE3MjIxfQ.6Jiolrgj4tPjErmflUaCVXHmXPXq44dFkorABK9niEw

{
  "title": "Sample Note",
  "content": "This is the content of the note."
}